# Generated by Django 5.2.4 on 2025-07-21 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('filas', models.IntegerField()),
                ('columnas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_salida', models.DateTimeField()),
                ('fehca_llegada', models.DateTimeField()),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado'), ('retrasado', 'Retrasado')], default='activo', max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviones.avion')),
            ],
        ),
    ]
