# Generated by Django 5.2.4 on 2025-08-06 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0002_delete_vuelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avion',
            name='capacidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='avion',
            name='columnas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='avion',
            name='filas',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('Economico', 'Economico'), ('Ejecutivo', 'Ejecutivo')], max_length=20)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('Ocupado', 'Ocupado')], default='Disponible', max_length=20)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviones.avion')),
            ],
        ),
    ]
