# Generated by Django 5.2.4 on 2025-07-31 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
    ]
