# Generated by Django 5.2.4 on 2025-08-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0002_alter_pasajero_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='nacionalidad',
        ),
        migrations.AddField(
            model_name='pasajero',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('Pasaporte', 'Pasaporte'), ('Otro', 'Otro')], default='Otro', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='documento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
