# Generated by Django 5.2.4 on 2025-08-06 22:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vuelos', '0002_alter_vuelo_destino_alter_vuelo_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePasajerosPorVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generado_por', models.CharField(max_length=100)),
                ('fecha_generacion', models.DateTimeField(default=datetime.datetime.now)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.vuelo')),
            ],
        ),
    ]
