# Generated by Django 5.2.4 on 2025-08-06 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_alter_vuelo_destino_alter_vuelo_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
