# Generated by Django 5.2.4 on 2025-08-06 22:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0003_alter_avion_capacidad_alter_avion_columnas_and_more'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='emitido',
        ),
        migrations.AddField(
            model_name='boleto',
            name='codigo_barra',
            field=models.CharField(default='SIN_CODIGO', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleto',
            name='estado',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Usado', 'Usado'), ('Cancelado', 'Cancelado')], default='pendiente', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleto',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada')], default='pendiente', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='asiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aviones.asiento'),
        ),
    ]
